#!/bin/sh

rm -f OUTPUT/*

# cp HOSTS HOSTS
cp CMDS1 CMDS

echo
echo RMB starting
echo

/usr/bin/time -p  ./p4 

#### not used in this demo
# echo
# echo RMB OUTPUT
# cat ../OUTPUT/*
# echo

echo
echo `pwd`  "  DONE"
echo
